### PR TITLE
Provide hover for `define macro

### PR DESCRIPTION
**Pull request by toastedcornflakes**
I was frustrated that the hover didn't provide macro definitions (`define FOO 8'hff), it's now working.

I also efactored the getComment function to simplify the way they're called.

### CODE REVIEW

**Comment by toastedcornflakes** [comment]
Ping :) Is there anything else I need to do to get this merged?

**Review by djoffe — APPROVED** [review]
I don't know much about GitHub process for approving pull requests. I suspect @mshr-h needs to approve them personally, but I will submit an Approve review to this pull request to see if the changes are integrated.

Sorry for the lack of critical feedback, I don't see how I would improve this code.

**Comment by mshr-h** [comment]
Ok.

**Comment by toastedcornflakes** [comment]
Woo thanks 😊

**Pull request merged**
